SPRT-147: Adding links to the images
PukaraES/Cicerone pull request #58
Opened 2022-08-09 18:40 UTC by PabloBerrettoni

Changes based on the issue https://pukarait.atlassian.net/browse/SPRT-147
Adding links to the images in the detail view

2022-08-09 19:02 UTC, njrzr requested changes

2022-08-09 19:02 UTC, njrzr commented on pages/places/_id/place-details.vue
> +          :class="['w-full', 'md:w-full', 'md:p-0', 'h-64', 'md:h-96', 'object-cover', 'rounded-lg', 'shadow-md', 'transition', { 'hidden': active !== index }]"
@PabloBerrettoni the rounded-lg, shadow-md and transition pass it to the anchor tag, and the md:w-full isn't needed and I guess the h-64 and md:h-96 can be passed too and change it in the height to h-full in the img tag. Check that these changes I commented doesn't break the page

2022-08-09 19:15 UTC, PabloBerrettoni commented on pages/places/_id/place-details.vue
> +          :class="['w-full', 'md:w-full', 'md:p-0', 'h-64', 'md:h-96', 'object-cover', 'rounded-lg', 'shadow-md', 'transition', { 'hidden': active !== index }]"
@njrzr The h-64 and md:h-64 had to stay in  the img class, but other thant that the changes worked correctly.

2022-08-09 22:00 UTC, njrzr approved these changes

2022-08-09 22:00 UTC, merged

2022-08-10 07:19 UTC, olea commented
The image URL is not the correct one. Check https://github.com/PukaraES/Cicerone/issues/24#issuecomment-1191398304.