change size of images on popups of map
PukaraES/Cicerone pull request #74
Opened 2022-08-17 22:41 UTC by facuzero

2022-08-18 07:10 UTC, olea reviewed
Can you share example screenshots, please?

2022-08-18 19:24 UTC, olea commented
This is a lot of better, but it fit images of any proportion in the same box size. What is needed is to scale the image to fit in the current box keeping the image proportions.

2022-08-23 22:41 UTC, njrzr commented
@facuzero what do you need to do here is to wrap the image on a div and set the width and height to the same size(square) and to the image add the utility of object-contain so that the image fits keeping his aspect ratios inside this wrapper.

2022-08-24 15:43 UTC, njrzr requested changes
@facuzero read the comment a made, and make the corresponding fixes.

2022-08-24 15:43 UTC, njrzr commented on components/WLMap.vue
> +                <l-popup class="w-40 h-40">
@facu what did you did here? You should have wrapped the img element with a div and add these utilities there, change it.

2022-08-24 15:43 UTC, njrzr commented on components/WLMap.vue
> +                    <div class="p-2 w-30 h-30 flex flex-wrap object-cover">
@facuzero object-cover doesn't go here, you have to add it to the img element, and is object-contain, not object-cover, and add the items-center and justify-center to center the elements.

2022-08-24 15:43 UTC, njrzr commented on components/WLMap.vue
> +                      <img :src="data.image != undefined ? data.image.value + '?width=320px' : '/images/default-image.jpg'" :class="['w-32, h-32']">
@facuzero what did you did here? you can add class without the colons, when the colons are used is for when using conditions, or the data object, and you should add here the object-contain.

2022-08-24 16:15 UTC, facuzero commented on components/WLMap.vue
> +                <l-popup class="w-40 h-40">
ok im gonna change

2022-08-24 16:34 UTC, facuzero commented on components/WLMap.vue
> +                      <img :src="data.image != undefined ? data.image.value + '?width=320px' : '/images/default-image.jpg'" :class="['w-32, h-32']">
@njrzr  I think everything is fixed

2022-08-24 17:53 UTC, olea commented
Checking 5a3b4ea3cb82f62f02d135a95e63839fca9e3206 there are differences in sizes:

![Captura desde 2022-08-24 19-49-20](https://user-images.githubusercontent.com/141267/186488998-24cf43ba-7729-4520-a1b6-562646037489.png)
![Captura desde 2022-08-24 19-49-12](https://user-images.githubusercontent.com/141267/186489026-954c0a8f-af90-4d37-84d2-8c1815263a15.png)
![Captura desde 2022-08-24 19-49-05](https://user-images.githubusercontent.com/141267/186489062-0a07e5f8-304b-4b34-aad8-0060c3821a83.png)

:-m

2022-08-25 10:43 UTC, olea commented
Checked 16a72c15ac5b0cbd488d763969ed965af8e19078
![image](https://user-images.githubusercontent.com/141267/186643921-cd6ba59d-eb6f-451c-bef2-14f46ab945bd.png)
![Captura desde 2022-08-25 12-36-23](https://user-images.githubusercontent.com/141267/186644025-9979ed46-03e9-401e-8333-de2a20b6a356.png)
![Captura desde 2022-08-25 12-35-45](https://user-images.githubusercontent.com/141267/186644042-f4b3918b-c8f4-4b23-b75c-afce54807ec4.png)
![Captura desde 2022-08-25 12-41-34](https://user-images.githubusercontent.com/141267/186644339-1e29f5e9-1ed8-4b6e-8e34-96adc5ab96f7.png)

You can check the same examples through the «Ubicación» box and selecting, for example, Q56064929, or any other WD item.

2022-08-25 16:40 UTC, njrzr approved these changes

2022-08-25 16:40 UTC, merged

2022-08-25 16:56 UTC, olea commented
Verificando 957bac32e64724f15f0b4ece4ccf0ff1fff1226c... todo parece correcto :-)