SPRT-146: Restoring the previous state.
PukaraES/Cicerone pull request #84
Opened 2022-09-12 13:48 UTC by PabloBerrettoni

Fixing some pagination problems suggested by @olea on this issue: [#27](https://github.com/PukaraES/Cicerone/issues/27)
When coming back from the detail view of the monuments you'll find the previos pagination and/or the previous location selected

2022-09-12 18:04 UTC, njrzr requested changes
@PabloBerrettoni checking the site I saw some issues, the first one is that when returning the miniatures the select is on the default state (monuments) instead of the selected one (I don't know if a priority to fix it), it should be the same when entered on the details miniature, the second one is when searching for another place and select it, in the map a marker icon is in place where the people icon is, but the people icon is underneath it, I don't know is this was added in this change or another, ask @facuzero for help, to change this and hide the people icon when this happens.

2022-09-12 19:07 UTC, PabloBerrettoni commented on components/WLCloseByMiniatures.vue
> +      console.log(this.$store.state)
@njrzr This was already fixed [here](https://github.com/PukaraES/Cicerone/pull/84/commits/1dca8312ac53566215fdeb4833127263627ef1d9)

2022-09-12 19:10 UTC, PabloBerrettoni commented
> @PabloBerrettoni checking the site I saw some issues, the first one is that when returning the miniatures the select is on the default state (monuments) instead of the selected one (I don't know if a priority to fix it), it should be the same when entered on the details miniature, the second one is when searching for another place and select it, in the map a marker icon is in place where the people icon is, but the people icon is underneath it, I don't know is this was added in this change or another, ask @facuzero for help, to change this and hide the people icon when this happens.

The second issue (the one about the marker) is an already existing issue. Maybe we can create another github issue to address that? Attaching image of that happening on cicerone.guide
![image](https://user-images.githubusercontent.com/78081626/189736071-c65b6960-3f31-4592-8e13-a411c2539b43.png)

2022-09-15 17:47 UTC, gnaomi0 commented
@PabloBerrettoni this is working for me. @njrzr Please check. Also, Pablo I think you can open a new issue about the marker thing.

2022-09-15 20:47 UTC, njrzr approved these changes

2022-09-15 20:47 UTC, merged